### ISSUE TITLE
sidplay requires hitting restore (panic) to change directories

### ISSUE THREAD

**Issue by seanlynch** [pi1541/Pi1541#114]
I'm using the SD2IEC version of sidplay to play HVSC off of an SD card, but I have to hit RESTORE to get it to list a new directory. Directory on the Pi's screen changes right away. I'm guessing this is due to some command or response code not being implemented. It would be great to have enough SD2IEC support for sidplay so that I don't have to somehow pack all the songs into disk images or use the much larger PSID-converted files, which don't work anyway right now because many are over 16 characters.

**Comment by seanlynch** [comment]
Works perfectly. Thanks!

**Comment by word** [comment]
The link to the patched sidplay is broken.  Is there anywhere else I can find it?

**Comment by jannekayra** [comment]
https://cbm-pi1541.firebaseapp.com/sidplaypi.prg
