### ISSUE TITLE
C128 hangs on boot/reset

### ISSUE THREAD

**Issue by penfold42** [pi1541/Pi1541#13]
If I unplug the iec cable it starts fine
If I hold C= tonforce 64 mode it’s also fine.

C128 supports autobioting - I wonder if it’s getting confused  by the Pi

**Comment by pi1541** [comment]
Last time I checked it was working. I will have to go through old builds and see when it broke.

**Comment by penfold42** [comment]
I also need to revalidate that this happens and how/when. Mainly wanted to flag it in case others saw it 

It’s a 128dcr with jiffydos and the internal drive is remapped to drive 11

**Comment by wernersv** [comment]
I can see this too when using HW option B. As soon as my C128DCR accesses a drive the system will hang. Cutting the power to the 7406 will continue the disk operation. There is no problem when using HW option A. 

1571 device 8
PI1541 device 9

**Comment by wernersv** [comment]
@penfold42, I had similar issues with mine created using prototyping board. Accessing the internal drive in either c128 or c64 mode did not work until the cable was unplugged. This was caused by some wires shorting. The short was fixes and it worked fine.

**Comment by xlar54** [comment]
Bump.  It freezes up completely on me in 128 mode (as if trying to autoboot).  Only 64 mode currently works.  Standard flat 128, no JD

**Comment by penfold42** [comment]
Hardware variant ?
Mines split lines

**Comment by pi1541** [comment]
Should be fixed in V1.12
It was trying to load the boot sector via direct access commands.

**Comment by penfold42** [comment]
Happy here !

Thanks
