### ISSUE TITLE
No piture on SSD1306 display

### ISSUE THREAD

**Issue by thErZAgH** [pi1541/Pi1541#15]
Hi Peter.

Some ppl -- including me -- are wondering how to connect the SSD1306 display on RPi3 the right way.

I connected VCC 3,3V, GND, SD and SC. SD on PIN (not GPIO) 27 and SC on PIN (not GPIO) 28.
My option.txt:

_LCDName = ssd1306_128x64
i2cBusMaster = 0 //SDA - pin 27 SCL - pin 28_

No picture. 

I bought this one:

https://www.amazon.de/AZDelivery-Display-Arduino-Raspberry-gratis/dp/B01L9GC470/ref=sr_1_1?ie=UTF8&qid=1528315648&sr=8-1

**Comment by penfold42** [comment]
Weird - I just tried mine with the latest git pull and it worked.

I tested both bus 1 and bus 0.

I2c needs PullUp resistors on the bus to work. Can you check if your display has resistors between sda and VCC and also between scl and VCC ?

**Comment by penfold42** [comment]
I’ve done some digging - I suspect many cheap Ebay ssd1306 do NOT include pull up resistors on sda and scl. Mine doesn’t.

I fiddled with mine and there was some corruption when used with pins 27/28.

The Pi HAS pull-ups on the spi bus on pins 3/5 but DOES NOT on 27/28.

I soldered on a pair of 4k7 pull up resistors and now the corruption appears to be fixed on mine.

**Comment by jgilcas** [comment]
Could be but at the moment mine is working in 27/28 only changing software software... mmmm i will try to add 4k7 pull up :)

![imagen](https://user-images.githubusercontent.com/37148968/41090105-bd10a040-6a43-11e8-8d84-eedb90a2476b.png)

**Comment by jgilcas** [comment]
All used by me had 0x3C, i used them in txzduino and tapuino :)

**Comment by penfold42** [comment]
The ssd1306 can only do two different i2c addresses - 0x3c and 0x3d.
Most have a resistor to select between them but it is marked as 0x78 / 0x7a (its the value shift left 1 bit)

As an aside, I’ve just created a PR to allow specifying the address in options.txt

**Comment by thErZAgH** [comment]
That could be another reason not to get a picture...

**Comment by 1c3d1v3r** [comment]
If you have a logic analyzer you can use it to check for an ACK (slave response to I2C communication, correct address etc.)

**Comment by thErZAgH** [comment]
Problem could be solved with 1.04 maybe. Will give a try if I'm at home in about one hour.

**Comment by jgilcas** [comment]
Versión 1.04 is working perfect for me, brilliant :) 🥇

**Comment by thErZAgH** [comment]
I kicked my compiled code I did myself. Now it works.
