### ISSUE TITLE
V1.21@Pi3: After mounting d81 image: Device not present error

### ISSUE THREAD

**Issue by hpingel** [pi1541/Pi1541#153]
Hi Steve,

In v1.21 I get a "Device not present error" after mounting a d81 image and doing LOAD"*",8,1. With v1.20 it works fine. I am using a Pi 3B as usual.

d64 images work fine.

Thank you for all your hard work!

Cheers,
Henning

**Comment by hpingel** [comment]
It looks to me that EXPERIMENTALZERO is set and therefore PI1581SUPPORT is not set.

#ifndef EXPERIMENTALZERO
#define PI1581SUPPORT 1
#endif

**Comment by hpingel** [comment]
Fixed by https://github.com/pi1541/Pi1541/pull/156

**Comment by pi1541** [comment]
Fixed in v1.22
