### ISSUE TITLE
toolchain download link for windows is invalid

### ISSUE THREAD

**Issue by Thraka** [pi1541/Pi1541#164]
>On Windows use GNU Tools ARM Embedded tool chain 5.4.1 using make. https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads/5-2016-q2-update

This link doesn't work I'm unsure if I can use the latest or that old 2016 version is what is required?

**Comment by hpingel** [comment]
I tried it with latest toolchain. Next missing component on Windows is GNU make. Better take a different approach: Linux subsystem on Windows 10. Get Ubuntu bash on Windows and use.it.

**Comment by Thraka** [comment]
I did that after I couldn't get the GNU Make to work :) Compiled no prob! I love the linux subsystem.
