### ISSUE TITLE
Cannot Flash ROM to EasyFlash 3

### ISSUE THREAD

**Issue by usenethound** [pi1541/Pi1541#169]
Using Kernel 1.23
Pi 3
pihat type B

When browsing directories to locate my cartridge ROMS, Easyflash 3 was not loading directories unless I hit F5 to refresh the listing each time I changed levels.

Once I got to my ROM to flash it to the EasyFlash 3 I pressed enter to flash the ROM (Action Replay 5 NTSC) but there is no response from the keyboard.

I then shut everything down and hooked up my SD2IEC+ and everything worked as it should. All directories loaded and the ROM flashed without issue.

**Comment by pi1541** [comment]
You need to put the ROMs into a D64 and mount that.
Pi1541 does not simulate fast loaders when it is browse mode only when it is full emulation mode.

**Comment by usenethound** [comment]
Thanks Steve, I will try that this weekend and report back :)

**Comment by usenethound** [comment]
Yep the files flash perfectly when put inside a .d64 image and put in emulation mode.

Thanks Steve!
