### ISSUE TITLE
Add drive number select by gpio

### ISSUE THREAD

**Issue by penfold42** [pi1541/Pi1541#2]

**Comment by andremiller** [comment]
Are you thinking along the lines of using a dip-switch to set the drive number?

**Comment by penfold42** [comment]
Yep

**Comment by pi1541** [comment]
With the split lines pin assignments and keeping away from SPI and I2C pins I think we are out of GPIO?

**Comment by penfold42** [comment]
Hmmmmm !

Maybe we could share the bidirectional lines with the split output lines ?

**Comment by pi1541** [comment]
We already are. See enum PIGPIO in iec_bus.h

**Comment by penfold42** [comment]
Done via USB keyboard and buttons
