### ISSUE TITLE
Domain name in readme has expired and is redirected to an "adult" site

### ISSUE THREAD

**Issue by borb** [pi1541/Pi1541#222]
Hello!

It appears that the pi1541.com domain has expired and I had a bit of a shock visiting to see the wiring instructions (hint: no wiring instructions, adult content).

May I suggest updating the readme to point to https://cbm-pi1541.firebaseapp.com/ instead? I can create a pull request for this 😃

**Comment by pi1541** [comment]
So sorry about that.
It has been fixed, thanks.
