### ISSUE TITLE
Hang/lockup after many hours

### ISSUE THREAD

**Issue by penfold42** [pi1541/Pi1541#23]
Left it running last night.
It’s Locked up hard this morning.

Has anyone else seen this ?
Want me to get some serial logging working ?

**Comment by thErZAgH** [comment]
Explain "Left it running". With an image mounted? Or without anything doing -- idle mode?

**Comment by penfold42** [comment]
I can’t remember if an image was mounted.

No 64 attached, but zoomfloppy probably was.

I know this is a crappy issue report - just thought I’d put it out here to see if others have seen it

**Comment by thErZAgH** [comment]
No problem. So ppl can compare if they have this issue, too.
