### ISSUE TITLE
Cant download old binaries ?

### ISSUE THREAD

**Issue by bugjacobs** [pi1541/Pi1541#230]
Hello ! 
I try to click on the "download old kernels" link on the firebaseapp main site, but it just links to "whats new" so I can't go back to v 1.23 for example ! 
Cheers and greets

**Comment by bugjacobs** [comment]
Brilliant and it was fixed !! Closing !

**Comment by h3r3** [comment]
This doesn't look fixed to me: on the website https://cbm-pi1541.firebaseapp.com/ the only link to "Old Versions" points to https://cbm-pi1541.firebaseapp.com/whatsnew.html which doesn't include any way to download older versions.
