### ISSUE TITLE
Question about CMD-HD

### ISSUE THREAD

**Issue by radius75** [pi1541/Pi1541#244]
Is it technically possible to emulate CMD-HD on pi1541 HAT?

**Comment by Deadweasel** [comment]
I mean, that's pretty much expecting a floppy drive to act like a hard drive instead, isn't it?

You have to forget the Pi's usual flexibility in this case.  When it's setup as a Pi1541, that's ALL it can do unless you pull out the SD card and swap in different software.

To have the Pi itself act as a hard drive, that's a whole unique project in itself, but one that I'm sure somebody is toying around with!
