### ISSUE TITLE
1306 oled garbled on startup with c64 off

### ISSUE THREAD

**Issue by pluto63** [pi1541/Pi1541#33]
With c64 off or disconected the oled after showing the disk drive image it doesn’t resets totally and remains garbled till you open the c64 and get a reset signal. It works fine when pi is powered while c64 is on, it displays the directory perfectly. Using option B schematic.

**Comment by penfold42** [comment]
Maybe related to #22

Hopefully I can look at what’s happening on the bus this weekend

**Comment by thErZAgH** [comment]
Hey @pluto63 : Please close this ticket. We have this in https://github.com/pi1541/Pi1541/issues/22
