### ISSUE TITLE
Add mode to GPIO (browser/emulation)

### ISSUE THREAD

**Issue by andremiller** [pi1541/Pi1541#4]
I think it would be nice to output the mode via GPIO(s) to drive a LED to indicate various states:

Booting Up
Browser Mode
Emulation Mode

This could be used to drive a second LED, possibly a RED/Green LED to indicate the various states / modes. A second LED next to the current activity LED would look nice in a case.

**Comment by penfold42** [comment]
We’ve kind of run out of gpio pins 8-(

Some ideas :
Hang it off a i2c port expander
Hang it off a SPI bus shift register
Use a WS2812 led bit bashed off the existing led pin 

@pi1541:
I’m a fan of ws2812 leds.
Are there some spare cycles in 2 of the 16MHz clock periods ?
I need to selectively set or clear a bit every ~350nS

**Comment by andremiller** [comment]
With OLED/LCD displays added I think this is no longer needed.
