### ISSUE TITLE
[1.15] issue with Epyx Fast Loader / Executing PRG

### ISSUE THREAD

**Issue by shazz** [pi1541/Pi1541#97]
Hi, I have some troubles with Fast Loader I don't have without:

test cases:
1. Autorun FB64.D64 from Fast Loader => ok
2. Select sidplay64_08.prg => hangs

1. Autorun FB64.D64 from Fast Loader => ok
2. Select sidplay64_test_disk.d64 => ok
3. Browse SID files from sidplay, located in directories (outside the d64 image) => ok
4 Select a SID file  => hangs

Same test cases without the Fast Loader work well

Thanks ! Awesome work !

**Comment by pi1541** [comment]
Epyx Fast Loader does not work in browse mode. As soon as you exit a disk image you are exiting back into browse mode.

**Comment by shazz** [comment]
Thanks !
